### ISSUE TITLE
split event data between upcoming and past

### ISSUE THREAD

**Issue by eemshi** [mmmanyfold/playground-coffeeshop#19]

**Comment by eemshi** [comment]
i'll add the tabs now

**Comment by eemshi** [comment]
@dviramontes should we have the sub-menu (Upcoming and Past) appear only when the mouse hovers over Events tab?

**Comment by dviramontes** [comment]
on `:hover` ? not a bad idea but i wonder if it makes it more tricky for the mobile menu. No `:hover` on mobile :/

**Comment by dviramontes** [comment]
although we can always use a media-query to disable it for mobile..

**Comment by eemshi** [comment]
Or expand on click rather than hover
